### ISSUE TITLE
Save fails when field with @SearchIndex(type = IndexType.DATE) has null value

### ISSUE THREAD

**Issue by mbyrne00** [3wks/spring-boot-gae#5]
Fix should be to not attempt to write value if null. Check all other types too.

```
java.lang.IllegalArgumentException: Cannot set date field to null.
	at com.google.appengine.repackaged.com.google.common.base.Preconditions.checkArgument(Preconditions.java:135) ~[appengine-api-1.0-sdk-1.9.59.jar:na]
	at com.google.appengine.api.search.Field$Builder.setDate(Field.java:139) ~[appengine-api-1.0-sdk-1.9.59.jar:na]
	at org.springframework.contrib.gae.search.conversion.FieldBuilder.setDate(FieldBuilder.java:131) ~[spring-boot-gae-1.0.0-beta-9.jar:na]
	at org.springframework.contrib.gae.search.conversion.FieldBuilder.lambda$apply$0(FieldBuilder.java:49) ~[spring-boot-gae-1.0.0-beta-9.jar:na]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[na:1.8.0_131]

```

**Comment by n15g** [comment]
Dates can't have a null value? I swear the list of what you can't do with search API far eclipses what you can.
Might want to add that to the list of restrictions in the readme file while you're at it.

**Comment by mbyrne00** [comment]
I think thundr just didn't call the setter if value was null. I did similar for `NUMBER` so we should probably do that for all in a higher piece of the code.

**Comment by n15g** [comment]
I think that makes the most sense from an expectation point.

It's hard to imagine a scenario where you *expect* the code to have a heart attack when you save a null... but it may cause issues if we silently ignore it, such as if the user ever tries to search for entries with null dates... though I expect the search operation is just as likely to throw an exception in that scenario.
